//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNPX_space.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNPX_space.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copy Bitmap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_CopyBitmap {
            get {
                return ResourceManager.GetString("btn_CopyBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_CreateAll {
            get {
                return ResourceManager.GetString("btn_CreateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_CreateAuto {
            get {
                return ResourceManager.GetString("btn_CreateAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_CreateManual {
            get {
                return ResourceManager.GetString("btn_CreateManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_CreatePuzzleAuto {
            get {
                return ResourceManager.GetString("btn_CreatePuzzleAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomePage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_HomePage {
            get {
                return ResourceManager.GetString("btn_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_InitialState {
            get {
                return ResourceManager.GetString("btn_InitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_MultiSolve {
            get {
                return ResourceManager.GetString("btn_MultiSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_MultiStop {
            get {
                return ResourceManager.GetString("btn_MultiStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standardization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Nomalize {
            get {
                return ResourceManager.GetString("btn_Nomalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_NumChange {
            get {
                return ResourceManager.GetString("btn_NumChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_NumChangeFix {
            get {
                return ResourceManager.GetString("btn_NumChangeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Puzzle File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_OpenPuzzleFile {
            get {
                return ResourceManager.GetString("btn_OpenPuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern generate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_PatternAutoGen {
            get {
                return ResourceManager.GetString("btn_PatternAutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_PatternCapture {
            get {
                return ResourceManager.GetString("btn_PatternCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_PatternClear {
            get {
                return ResourceManager.GetString("btn_PatternClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_ProbNxt {
            get {
                return ResourceManager.GetString("btn_ProbNxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_ProbPre {
            get {
                return ResourceManager.GetString("btn_ProbPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Bitmap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_SaveBitmap {
            get {
                return ResourceManager.GetString("btn_SaveBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_SavePuzzle {
            get {
                return ResourceManager.GetString("btn_SavePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_SaveToFavorites {
            get {
                return ResourceManager.GetString("btn_SaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Solve {
            get {
                return ResourceManager.GetString("btn_Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_SolveUp {
            get {
                return ResourceManager.GetString("btn_SolveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_TransEst {
            get {
                return ResourceManager.GetString("btn_TransEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_TransLRg {
            get {
                return ResourceManager.GetString("btn_TransLRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   to Beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_TransRes {
            get {
                return ResourceManager.GetString("btn_TransRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clockwise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_TransRtg {
            get {
                return ResourceManager.GetString("btn_TransRtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_TransUDg {
            get {
                return ResourceManager.GetString("btn_TransUDg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Undo {
            get {
                return ResourceManager.GetString("btn_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomePage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnP_HomePage {
            get {
                return ResourceManager.GetString("btnP_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Algorithm List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chb_AddAlgorithmList {
            get {
                return ResourceManager.GetString("chb_AddAlgorithmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DigitsColoring に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chb_DigitsColoring {
            get {
                return ResourceManager.GetString("chb_DigitsColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format : Line type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chb_FormatLine {
            get {
                return ResourceManager.GetString("chb_FormatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Difficulty Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chb_SortByDiffOrder {
            get {
                return ResourceManager.GetString("chb_SortByDiffOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Initial State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbInitialState {
            get {
                return ResourceManager.GetString("chbInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save with Answer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSaveWithAnswer {
            get {
                return ResourceManager.GetString("chbSaveWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching all solutions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbSearchingAllSolutions {
            get {
                return ResourceManager.GetString("chbSearchingAllSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_SetDifficulty {
            get {
                return ResourceManager.GetString("chbx_SetDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm multiple cells に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_ConfirmMultipleCells {
            get {
                return ResourceManager.GetString("chbx_ConfirmMultipleCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Output on Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_FileOutputOnSuccess {
            get {
                return ResourceManager.GetString("chbx_FileOutputOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   show Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_NrmlNum {
            get {
                return ResourceManager.GetString("chbx_NrmlNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Randomizing Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_RandomizingNumbers {
            get {
                return ResourceManager.GetString("chbx_RandomizingNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_SetAnswer {
            get {
                return ResourceManager.GetString("chbx_SetAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Candidate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_ShowCandidate {
            get {
                return ResourceManager.GetString("chbx_ShowCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show noused digits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_ShowNoUsedDigits {
            get {
                return ResourceManager.GetString("chbx_ShowNoUsedDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_ShowSolution {
            get {
                return ResourceManager.GetString("chbx_ShowSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chbx_WhiteBack {
            get {
                return ResourceManager.GetString("chbx_WhiteBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefer simple に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chkPreferSimpleLinks {
            get {
                return ResourceManager.GetString("chkPreferSimpleLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use eALS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string chkUse_eALS {
            get {
                return ResourceManager.GetString("chkUse_eALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string filePuzzleFile {
            get {
                return ResourceManager.GetString("filePuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SuDoKu_Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fldSuDoKuImages {
            get {
                return ResourceManager.GetString("fldSuDoKuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string gbx_MSearchCondition {
            get {
                return ResourceManager.GetString("gbx_MSearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Omit multiple candidates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenLS_turbo {
            get {
                return ResourceManager.GetString("GenLS_turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_AlgorithmM {
            get {
                return ResourceManager.GetString("lbl_AlgorithmM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_ALSSizeMax {
            get {
                return ResourceManager.GetString("lbl_ALSSizeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_AppliedCount {
            get {
                return ResourceManager.GetString("lbl_AppliedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_CellsPuzzle {
            get {
                return ResourceManager.GetString("lbl_CellsPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_CellsSolved {
            get {
                return ResourceManager.GetString("lbl_CellsSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnSolved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_CellsUnsolved {
            get {
                return ResourceManager.GetString("lbl_CellsUnsolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_ChangeNumber {
            get {
                return ResourceManager.GetString("lbl_ChangeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_ClickOnNumber {
            get {
                return ResourceManager.GetString("lbl_ClickOnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create / Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_CreateEdit {
            get {
                return ResourceManager.GetString("lbl_CreateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_DifficultyM {
            get {
                return ResourceManager.GetString("lbl_DifficultyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Rank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_GenLogMaxRank {
            get {
                return ResourceManager.GetString("lbl_GenLogMaxRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_GenLogMaxSize {
            get {
                return ResourceManager.GetString("lbl_GenLogMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_LapTimeTS3 {
            get {
                return ResourceManager.GetString("lbl_LapTimeTS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lbl_Maximum {
            get {
                return ResourceManager.GetString("Lbl_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lbl_Method {
            get {
                return ResourceManager.GetString("Lbl_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Methods applied to the Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_MethodApply {
            get {
                return ResourceManager.GetString("lbl_MethodApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_MSlvrMaxLevel {
            get {
                return ResourceManager.GetString("lbl_MSlvrMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_NLMaxSize {
            get {
                return ResourceManager.GetString("lbl_NLMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cum. Trials: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_NoOfTrialsCum {
            get {
                return ResourceManager.GetString("lbl_NoOfTrialsCum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lbl_onAnalyzing {
            get {
                return ResourceManager.GetString("Lbl_onAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle Level: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_PuzzleLevel {
            get {
                return ResourceManager.GetString("lbl_PuzzleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_PuzzlePattern {
            get {
                return ResourceManager.GetString("lbl_PuzzlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random Seed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_RandomNumberSeed {
            get {
                return ResourceManager.GetString("lbl_RandomNumberSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (0:Auto 0&gt;:seed Seting) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_SeedSetting {
            get {
                return ResourceManager.GetString("lbl_SeedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzles Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lbl_SolveMarking {
            get {
                return ResourceManager.GetString("Lbl_SolveMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transformation(Asymmetric) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_TransAsymetric {
            get {
                return ResourceManager.GetString("lbl_TransAsymetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transformation(Symmetric) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_TransSymetric {
            get {
                return ResourceManager.GetString("lbl_TransSymetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AllSearchOption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAllSearchOption {
            get {
                return ResourceManager.GetString("lblAllSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chain Max. Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblALSChainSizeMax {
            get {
                return ResourceManager.GetString("lblALSChainSizeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblAnalysisLevel {
            get {
                return ResourceManager.GetString("lblAnalysisLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   difficulty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblDifficulty {
            get {
                return ResourceManager.GetString("lblDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed Time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblElapsedTime {
            get {
                return ResourceManager.GetString("lblElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblForceChainType {
            get {
                return ResourceManager.GetString("lblForceChainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblGNLType {
            get {
                return ResourceManager.GetString("lblGNLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection Methos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMethodSelect {
            get {
                return ResourceManager.GetString("lblMethodSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method is set by Solve/Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMethodSetting {
            get {
                return ResourceManager.GetString("lblMethodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMinimum {
            get {
                return ResourceManager.GetString("lblMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMSlvr_MaxNoAlgorithm {
            get {
                return ResourceManager.GetString("lblMSlvr_MaxNoAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMSlvr_MaxNoAllAlgorithm {
            get {
                return ResourceManager.GetString("lblMSlvr_MaxNoAllAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblMSlvrMaxTime {
            get {
                return ResourceManager.GetString("lblMSlvrMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cells:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfCells {
            get {
                return ResourceManager.GetString("lblNoOfCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzles: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfPuzzles {
            get {
                return ResourceManager.GetString("lblNoOfPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trials: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfTrials {
            get {
                return ResourceManager.GetString("lblNoOfTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblNoOfTrialsCanceled {
            get {
                return ResourceManager.GetString("lblNoOfTrialsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPattern {
            get {
                return ResourceManager.GetString("lblPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzle {
            get {
                return ResourceManager.GetString("lblPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle Creation Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzleCreationType {
            get {
                return ResourceManager.GetString("lblPuzzleCreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (0: Standard 1: High speed 2:Exhaustive search ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblPuzzleCreationType2 {
            get {
                return ResourceManager.GetString("lblPuzzleCreationType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveAll {
            get {
                return ResourceManager.GetString("lblSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current puzzle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblSaveCurrentPuzzle {
            get {
                return ResourceManager.GetString("lblSaveCurrentPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblSearchOption {
            get {
                return ResourceManager.GetString("LblSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lbl_Step {
            get {
                return ResourceManager.GetString("lbl_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblStepM {
            get {
                return ResourceManager.GetString("lblStepM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgAnalysisComplate {
            get {
                return ResourceManager.GetString("msgAnalysisComplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are cells with no candidate digits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNoSolution {
            get {
                return ResourceManager.GetString("msgNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSuspend {
            get {
                return ResourceManager.GetString("msgSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper Limit Break に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUpperLimitBreak {
            get {
                return ResourceManager.GetString("msgUpperLimitBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper Limit Time Break に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUpperLimitTimeBreak {
            get {
                return ResourceManager.GetString("msgUpperLimitTimeBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Symmetry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel00 {
            get {
                return ResourceManager.GetString("rdb_patSel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Symmetry (90 degrees) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel01 {
            get {
                return ResourceManager.GetString("rdb_patSel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Symmetry (180 degrees) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel02 {
            get {
                return ResourceManager.GetString("rdb_patSel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (Vertical) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel03 {
            get {
                return ResourceManager.GetString("rdb_patSel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (Horizontal) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel04 {
            get {
                return ResourceManager.GetString("rdb_patSel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (TL-BR) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel05 {
            get {
                return ResourceManager.GetString("rdb_patSel05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Symmetry (TR-BL) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rdb_patSel06 {
            get {
                return ResourceManager.GetString("rdb_patSel06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabACreate {
            get {
                return ResourceManager.GetString("tabACreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAFile {
            get {
                return ResourceManager.GetString("tabAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabAOption {
            get {
                return ResourceManager.GetString("tabAOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabASolve {
            get {
                return ResourceManager.GetString("tabASolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transform に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabATransform {
            get {
                return ResourceManager.GetString("tabATransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMethod {
            get {
                return ResourceManager.GetString("tabBMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMethodOption {
            get {
                return ResourceManager.GetString("tabBMethodOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MultiSolve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBMultiSolve {
            get {
                return ResourceManager.GetString("tabBMultiSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tabBSolve {
            get {
                return ResourceManager.GetString("tabBSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PuzzleSelection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_SolvePuzzleSelection {
            get {
                return ResourceManager.GetString("btn_SolvePuzzleSelection", resourceCulture);
            }
        }
    }
}
